#!/bin/bash

#Turn on power LED

if [ ! -d /sys/class/gpio/gpio27 ]
then
        echo "turning on LED"
        echo "27" > /sys/class/gpio/export
        sleep 0.1;
fi
echo "out" > /sys/class/gpio/gpio27/direction
echo "1" > /sys/class/gpio/gpio27/value
