#!/bin/bash

#Turn on power LED

if [ ! -d /sys/class/gpio/gpio4 ]
then
        echo "turning on LED"
        echo "4" > /sys/class/gpio/export
        sleep 0.1;
fi
echo "out" > /sys/class/gpio/gpio4/direction
echo "1" > /sys/class/gpio/gpio4/value
