#!/bin/bash
cd /usr/bin/photup
/usr/bin/git pull origin master >> /usr/bin/photup/git_update_log.txt
/usr/bin/pip3 install -r /usr/bin/photup/requirements.txt >> /usr/bin/photup/pip_update_log.txt

python3 /usr/bin/photup/photup.py > /usr/bin/photup/photuplog.txt

